### ISSUE TITLE
Prevent installation via Drush if API Docs module is installed

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#10]
Mentioned in #7, Drush does not respect hook_requirements so this module can be installed when API Docs module is already installed if you use Drush to enable this module.

This issue is to add a way to stop Drush from allowing you to install this module if API Docs submodule of Apigee Edge is already enabled.

**Comment by Jaesin** [comment]
This is only an issue with Drush 9.

Drush 8 has been tested and will block the install of the Apigee API Catalog module if the Apigee Edge API Docs module is already installed.

**Comment by cnovak** [comment]
Closing this issue via PR #7
