### ISSUE TITLE
@ContentEntityType annotation is missing control handler and permission handler

### ISSUE THREAD

**Issue by jannakha** [apigee/apigee-api-catalog-drupal#101]
just add to apigee_api_catalog/src/Entity/ApiDoc.php:
 *    "access" = "Drupal\Core\Entity\EntityAccessControlHandler",
 *    "permission_provider" = "Drupal\Core\Entity\EntityPermissionProvider"

**Comment by jannakha** [comment]
actually, "access" = "Drupal\apigee_api_catalog\Entity\Access\ApiDocAccessControlHandler" doesn't exist :(

**Comment by jannakha** [comment]
now, how can I create a patch for it?

**Comment by arlina-espinoza** [comment]
@jannakha Thank you for reporting this, however, the ApiDoc custom entity isn't used anymore in the module and has been marked as deprecated, all UI relating to it has been removed too. It only exists in the codebase to allow users to update from the 1.x branch of the module that used it to the 2.x branch that uses nodes as the API Doc entity.
Please use the `apidoc` node type as the API Doc entity.
