### ISSUE TITLE
Update "Expose REST APIs to interact with API Docs" documentation using D9

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-api-catalog-drupal#105]
Verify and update as needed the documentation page, running it against Drupal 9: [Expose REST APIs to interact with API Docs](https://www.drupal.org/docs/contributed-modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs)
Follow D9 installation instructions from https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/get-started-with-kickstart#s-installation-instructions

**Comment by zakiya** [comment]
Currently blocked by https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/394#issuecomment-715610481

**Comment by zakiya** [comment]
I no longer hit the error from[ Kickstart #394](https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/394#issuecomment-715610481) but during installation of jsonapi_extras I hit an error that was coming from core. I[ re-rolled the patch that was included in the composer.json](https://www.drupal.org/project/drupal/issues/3042467#comment-13917262
).

The patch will need to be applied to the kickstarter composer file. @arlina-espinoza Is there an existing task I should put this info in or should I create a new one?

**Comment by arlina-espinoza** [comment]
@zakiya Thanks, lets detail on the comments what updates would need to be made to the [docs](https://www.drupal.org/docs/contributed-modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs). Does the patch that you re-rolled apply to both D8 and D9?

**Comment by zakiya** [comment]
The Drupal.org documentation [Expose REST APIs to interact with API Docs](https://www.drupal.org/docs/contributed-modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs) and has been tested and updated accordingly.

**Comment by arlina-espinoza** [comment]
Closing this issue, thanks @zakiya !
