### ISSUE TITLE
Issues with previous version of API Catalog cause issues when trying to upgrade to the Fix.

### ISSUE THREAD

**Issue by cbzdok** [apigee/apigee-api-catalog-drupal#109]
Issues created with the previous version of the API Catalog that were corrected in the following build, Apigee API catalog 8.x-2.4 , are unable to be resolved and are preventing me from updating to that build due to the errors below. I am unable to uninstall or upgrade any module as this error is always thrown. I am hoping to get the new version of Apigee API Catalog to resolve all of the issues we've had with it.

[01-Oct-2020 17:43:49 UTC] Uncaught PHP Exception
Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: "The
"apidoc" entity type did not specify a access handler." at
/code/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 272
[01-Oct-2020 17:46:11 UTC] Uncaught PHP Exception
Drupal\Core\Database\DatabaseExceptionWrapper: "SQLSTATE[42S02]: Base table
or view not found: 1146 Table 'pantheon.apidoc' doesn't exist: SELECT
base_table.revision_id AS revision_id, base_table.id AS id
FROM
{apidoc} base_table
GROUP BY base_table.revision_id, base_table.id
LIMIT 1 OFFSET 0; Array
(
)
" at /code/web/core/lib/Drupal/Core/Database/Connection.php line 701
[01-Oct-2020 17:49:42 UTC] Uncaught PHP Exception
Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: "The
"apidoc" entity type did not specify a access handler." at
/code/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 272

**Comment by arlina-espinoza** [comment]
Hi @cbzdok ,

The `apidoc` access control handler class was added back on the latest 8.x-2.4 release (https://github.com/apigee/apigee-api-catalog-drupal/pull/108), so I can't see why you'd be getting that error unless your site has cached entity definitions. Could you try clearing your cache a couple of times and try again?

**Comment by cbzdok** [comment]
Yes i've tried to clear the cache and it has not resolved the error.

**Comment by giteshk** [comment]
Here is what I did to fix my site.

Upgraded all the modules using

> composer update --with-dependencies -o


ran through the drupal updates.

> drush updb -y

Delete the following files which are deprecated:

> web/modules/contrib/apigee_api_catalog/src/Entity/Access/ApiDocAccessControlHandler.php
> web/modules/contrib/apigee_api_catalog/src/Entity/Routing/ApiDocHtmlRouteProvider.php
> web/modules/contrib/apigee_api_catalog/src/Entity/ApiDoc.php
> web/modules/contrib/apigee_api_catalog/src/Entity/ApiDocInterface.php
>

**Comment by giteshk** [comment]
@arlina-espinoza I think even if the "apidoc" entity is marked as depreacated. Drupal tries to look for the base_table of that entity.

Instead of deleting the entitytype in update8805 we can leave this table and remove in a future 3.x ?

**Comment by arlina-espinoza** [comment]
@giteshk Yes, I have submitted a PR that does that (#110). 
@cbzdok Feel free to test the fix in the PR and let us know if it works for you.
