### ISSUE TITLE
Getting Error on API Documentation settings page

### ISSUE THREAD

**Issue by nishasw** [apigee/apigee-api-catalog-drupal#122]
## Description
While accessing path /admin/structure/apidoc , I am getting the error below post installation of apigee kickstart module on both Drupal 8 & 9

The website encountered an unexpected error. Please try again later.

InvalidArgumentException: Class "Drupal\apigee_api_catalog\Entity\Form\ApiDocSettingsForm" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 24 of core\lib\Drupal\Core\DependencyInjection\ClassResolver.php).
Drupal\Core\Controller\HtmlFormController->getFormObject(Object, 'Drupal\apigee_api_catalog\Entity\Form\ApiDocSettingsForm') (Line: 58)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 158)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 706)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

Any help to resolve this will greatly be appreciated.

## Steps to Reproduce
1. Go to /admin/structure/apidoc and I get the error

![image](https://user-images.githubusercontent.com/78082773/105984630-1567ec00-60a3-11eb-9226-8611cd5cc7ae.png)

**Comment by cnovak** [comment]
For issue #2, it is a duplicate of: #67

**Comment by raakesh-blokhra** [comment]
Hi @nishasw I am looking at issue #123. 
Since @shishir-intelli has given steps to add API Doc, I'll close this ticket. Feel free to reopen in case you are still having any issues with creating API docs.

**Comment by raakesh-blokhra** [comment]
Since we don't have a configuration option for this feature anymore, the link in the admin needs for module config needs to be removed. Reopening this issue, will close with a PR.
