### ISSUE TITLE
Apigee API catalog not displaying in Drupal 9.1.7 after its module installation

### ISSUE THREAD

**Issue by jyotierudkar** [apigee/apigee-api-catalog-drupal#125]

**Comment by shishir-intelli** [comment]
Hi @jyotierudkar 
Can you please elaborate the issue in detail by providing us the steps to reproduce this issue and actual behavior & expected behavior.

**Comment by shishir-intelli** [comment]
After installing and enabling the module, you can create new API doc from `/node/add/apidoc` and can check the same on APIs Catalog page `/apis`.

Closing this ticket for now, If in case, you are still facing issue feel free to reopen it.
