### ISSUE TITLE
Issue with Drupal Apigee contributed module Upgrade.

### ISSUE THREAD

**Issue by ac46471** [apigee/apigee-api-catalog-drupal#127]
I have been trying to update apigee contributed modules. I am having some issue while updating the modules.  I have put more details below.

Drupal  version: 8.9.15

Updated Modules :
apigee/apigee_devportal_kickstart  1.16.0  —> 1.22
drupal/apigee_api_catalog 1.2.0 —>  2.5.0
drupal/apigee_edge 1.20.0 -> 1.21.0

Steps Followed:

   1.     composer self-update >> Tried with composer version 1.10 and 2.0.13
   2.    composer update --with-dependencies --optimize-autoloader >> with this some modules are not updated. So, went ahead and  changed version in composer.json file. Then ran same script again.
   3.    drush updb 

 

Error on running drush updb:

> [notice] Update started: apigee_api_catalog_update_8803

> [error] Attempt to create a field storage with an name longer than 32 characters: field_web_hooks_push_notificatio_apidoc

> [error] Update failed: apigee_api_catalog_update_8803

and I also tried deleting all the additional fields added to api doc. Then tried to upgrade.I was still getting error

[error] Update failed: call to member function getValue() on null.

**Comment by phdhiren** [comment]
@ac46471 
Can you share MariaDB / MySQL version as well? It may be related to core issue https://www.drupal.org/node/2565931

**Comment by edpahang** [comment]
@phdhiren
I work with @ac46471.  The MySQL version our team is using is Database Version 8.0.19
Let us know if you need more information.

**Comment by phdhiren** [comment]
@ac46471 @edpahang 
I'm able to replicate the issue. It seems due to the longer custom field name. Will check this further for resolution.

**Comment by edpahang** [comment]
@phdhiren 
Thanks for the update.  We appreciate you looking into this issue.
