### ISSUE TITLE
Make OpenAPI Specifications File field Translatable

### ISSUE THREAD

**Issue by sumansanjeet** [apigee/apigee-api-catalog-drupal#128]
Hello Team,

I am working on Drupal (version 8.x) multilingual portal and there is requirement to make APIDOC multilingual. I am looking into a way to translate OpenAPI Specifications File field in APIDOC entity  but i am not getting any option to do that. Can you please suggest a way to translate this field.

Thanks,
Sanjeet

**Comment by sumansanjeet** [comment]
This feature is available in latest version of Apigee API Catalog module. We can close this issue. Thanks.

**Comment by phdhiren** [comment]
Thanks for confirming
