### ISSUE TITLE
"Re-import OpenApi Spec" tab doesn't work 

### ISSUE THREAD

**Issue by hollyhw99** [apigee/apigee-api-catalog-drupal#132]
## Description
Hi, We are currently on Drupal core 8.9.17, and there is a new Tab showing up in recent deployment. 
It is "Re-import OpenApi Spec" tab for any object which has the swagger file. However, this tab seems to have no function. 

## Steps to Reproduce
Go to any product or category which has a swagger file, and this Tab is there. There is no file uploading feature under this tab. seems like a useless tab. 

## Screenshots
attached 

## Version Info
Drupal core 8.9.17
![Screen Shot 2021-08-04 at 3 00 03 PM](https://user-images.githubusercontent.com/36746092/128260879-07f624a2-1e3f-4c72-84f9-e8628178c20c.png)

**Comment by phdhiren** [comment]
A "Re-import OpenAPI spec" operation is available per API Doc to re-import the spec file when source location changes.

You can checkout more about in the documentation at https://www.drupal.org/docs/8/modules/apigee-api-catalog/document-your-apis#s-edit-anapi-doc

**Comment by phdhiren** [comment]
@hollyhw99  Closing this issue, feel free to reopen if require.
