### ISSUE TITLE
API Catalog does not render API documentation when using YML specs.

### ISSUE THREAD

**Issue by wongjoey** [apigee/apigee-api-catalog-drupal#152]
## Description
When creating a new API to be published in Drupal, the plugin (see screenshot) indicates that yml, yaml and json are allowed.

## Steps to Reproduce
1. Login as admin
2. Click on Content > API Catalog
3. Click on Add API Doc
4. Fill in the mandatory fields
5. Change Specification source type to File and select a spec file with extension of yml.
6. Click Save
7. Navigate back to API Catalog and click on the newly created API Doc.

## Actual Behavior
The detailed API Doc page does not render any of the API spec (i.e. blank API page is displayed)

## Expected Behavior
The detailed API Doc page should render all the resources and verbs of the API spec correctly.

## Screenshots
![image](https://user-images.githubusercontent.com/13177125/148878927-52ed4d09-6476-4b18-a5d4-f217b1722915.png)
![image](https://user-images.githubusercontent.com/13177125/148878897-848aaf89-5fe7-4253-b2f7-8e74536a68bc.png)

## Notes
Used kickstart profile in docker example provided on https://github.com/apigee/docker-apigee-drupal-kickstart

## Version Info
Version: 8.x-2.6

**Comment by raakesh-blokhra** [comment]
We are working on this issue. We will support *.yaml (YAML) file extensions and not *.yml as YAML is the preferred choice.

**Comment by mhottinger1** [comment]
Would it be possible to re-open this? Only having support for .yaml is a bit limiting since .yml is definitely a valid file extension for YAML files.

**Comment by raakesh-blokhra** [comment]
Hi @mhottinger1, as mentioned earlier, we do not plan to add support for *.yml. IF that changes, we will definitely reopen and confirm.

**Comment by VladimirAus** [comment]
This issue was contributed as security issue with no justification or due diligence. 🤷
