### ISSUE TITLE
Creating  API Doc using File URL, gives validation error : URI is not valid. It works fine with File Upload only.

### ISSUE THREAD

**Issue by samhaldia** [apigee/apigee-api-catalog-drupal#171]
## Description
When we try to create API Doc using File URI, it gives URI is not valid. It works fine with File Upload only.

## Steps to Reproduce
1. Go to 'node/add/apidoc' and enter other required fields
2. Select Specification source type 'URL'
3. Enter Value of URL to OpenAPI specification file ex: 'https://petstore.swagger.io/v2/swagger.yaml'

## Actual Behavior
It gives 'https://petstore.swagger.io/v2/swagger.yaml is not a valid link'

## Expected Behavior
It should parse URL and create API Doc from URL.

## Screenshots
![image](https://user-images.githubusercontent.com/11740959/159025101-ccf6de49-5c23-4d73-a2a0-289c4ccfd1d1.png)

## Version Info
apigee_api_catalog:8.x-2.6
Drupal Core: 9.2.8
PHP: 7.4.20

**Comment by phdhiren** [comment]
@samhaldia 

Can you check connection between your server and petstore.swagger.io server? Above is valid and should work.

**Comment by samhaldia** [comment]
@phdhiren 

Thanks yes it was the firewall blocking it. 
Is there way to customize the module to use authorization headers to allow URL to pass.

**Comment by samhaldia** [comment]
@phdhiren

Thanks yes it was the firewall blocking it. The flow is as designed not a bug. Thanks for providing input
Is there way to customize the module to use authorization headers to allow URL to pass?

**Comment by samhaldia** [comment]
@phdhiren

Thanks yes it was the firewall blocking it. The flow is as designed not a bug. Thanks for providing input
Is there way to customize the module to use authorization headers to allow URL to pass in such case?
