### ISSUE TITLE
The API File Link option uses again file storage locally to write and read the API 

### ISSUE THREAD

**Issue by samhaldia** [apigee/apigee-api-catalog-drupal#185]
## Is your feature request related to a problem? Please describe.
When we create New API Doc using File Link fields Option cinsidering the stoarge at remote. Eventually it stores back the file back to file storage field and renders back from there

## Describe the solution you would like
Read the file from url dynamicaaly instead of storage locally back and create API Doc

## Describe alternatives you've considered
Render the API Doc file from file link and display dynamically instead of storage to local filesystem again.

**Comment by shishir-intelli** [comment]
Hi @samhaldia ,

Sorry but we do not currently support remote storage. If anything changes on our roadmap, we will let you know.
Closing this ticket for now.
