### ISSUE TITLE
Access control for API Docs

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#19]
The API Catalog should have access control to control who can see each API Doc.  The Apigee Edge API Product should be an attribute of each API Doc so that an administrator can decide to hide API Docs for certain API Products.

**Comment by amcginn** [comment]
I see that this is for associating an API Doc to a Product. Is there a way to use taxonomy term control access within Drupal as you can with content types?

**Comment by cnovak** [comment]
> I see that this is for associating an API Doc to a Product. Is there a way to use taxonomy term control access within Drupal as you can with content types?

I believe we tried using taxonomy access control and it was not working because it only works with nodes, not any entity.  Would be good to revisit. Let us know if you find a solution around this using other modules and config @amcginn

**Comment by kscheirer** [comment]
https://www.drupal.org/project/permissions_by_term works well when you enabled its sub-module Permissions by Entity.

Views behavior is not quite what is expected, see #55, but otherwise seems to work.
