### ISSUE TITLE
Is there any way to post content to api catalog through apis?

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-api-catalog-drupal#199]
Hi, I am using jsonapi to post content but i am not able to post yaml file. Is there a way where i can upload my apidoc to the portal through my CI/CD?

**Comment by giteshk** [comment]
@simantstha We have a maven plugin that can be used to upload docs using a pipeline
Please take a look at https://github.com/apigee/apigee-smartdocs-maven-plugin/tree/master/samples/Drupal8

**Comment by simantstha** [comment]
Hey @giteshk, Thank you for your response. I know about that plugin but the feature i wanted to explore as you have more experience on it. How do i revert to previous version from a api call or may be a line of command. As i know i can always revert back from UI but i wanted to know if it is possible or if there are some tools. I found with jsonapi_Extras module i can just fetch revision. Also if we can connect somewhere else i have some series of questions.
