### ISSUE TITLE
Error editing an API Product from the API Catalog

### ISSUE THREAD

**Issue by edpahang** [apigee/apigee-api-catalog-drupal#201]
## Description
Route "view.apigee_api_catalog.page_1" does not exist.

## Steps to Reproduce
1. Upgrading Kickstart using https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/get-started-with-kickstart#s-upgrading-kickstart and https://github.com/apigee/devportal-kickstart-project-composer/blob/9.x/composer.json
2. Copied and updated the composer.json to add previous required modules
3. Login as an Admin and went to - /edit?destination=/admin/content/apis

## Actual Behavior
When trying to edit an API Product, we are seeing this message - The website encountered an unexpected error. Please try again later.

Here is the log messages:
ymfony\Component\Routing\Exception\RouteNotFoundException: Route "view.apigee_api_catalog.page_1" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of /opt/api_marketplace/APIEnable-apigee_dev_portal/web/core/lib/Drupal/Core/Routing/RouteProvider.php).

Drupal\Core\Routing\UrlGenerator->getRoute('view.apigee_api_catalog.page_1') (Line: 270)
Drupal\Core\Routing\UrlGenerator->generateFromRoute('view.apigee_api_catalog.page_1', Array, Array, 1) (Line: 105)
Drupal\Core\Render\MetadataBubblingUrlGenerator->generateFromRoute('view.apigee_api_catalog.page_1', Array, Array, ) (Line: 765)
Drupal\Core\Url->toString() (Line: 1765)
template_preprocess_breadcrumb(Array, 'breadcrumb', Array)
call_user_func_array('template_preprocess_breadcrumb', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('breadcrumb', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 80)
__TwigTemplate_6964c168452bf2a4acde155f791b9fd443ea471dc280844b972fe5af095c8a70->block_content(Array, Array) (Line: 182)
Twig\Template->displayBlock('content', Array, Array) (Line: 68)
__TwigTemplate_6964c168452bf2a4acde155f791b9fd443ea471dc280844b972fe5af095c8a70->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('core/themes/seven/templates/classy/block/block.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('block', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 55)
__TwigTemplate_53d0ed68e79f672aaf9a6d6d8acfed3f59dc6922906083bd7ba00b3642836e3b->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('core/themes/seven/templates/page.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('page', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 86)
__TwigTemplate_f3823526ddbf04b2651575af0ee8e54e2a37ca4a99646e40f27029effd885eb4->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('core/themes/seven/templates/classy/layout/html.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 162)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 163)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 709)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

## Expected Behavior
Should be able to edit an existing API Product in the API Catalog from the Admin UI.

## Version Info
composer.json before the upgrade:
"require": {
        "php": "^7.4",
        "apigee/apigee_devportal_kickstart": "^1.22",
        "bower-asset/swagger-ui": "^3.25",
        "composer/installers": "^1.2",
        "cweagans/composer-patches": "^1.6.5",
        "drupal/admin_toolbar": "^2.2",
        "drupal/adobe_launch": "^2.0",
        "drupal/apigee_api_catalog": "^2.5.0",
        "drupal/apigee_edge": "^1.26",
        "drupal/apigee_m10n": "^1.6.0",

composer.json after the upgrade:
"require": {
        "php": "^7.4 || ^8.0",
        "apigee/apigee_devportal_kickstart": "^2",
        "bower-asset/swagger-ui": "^3.25",
        "composer/installers": "^1.9",
        "cweagans/composer-patches": "^1.6.5",
        "drupal/admin_toolbar": "^3.0",
        "drupal/adobe_launch": "^2.0",
        "drupal/apigee_api_catalog": "^3.0",
        "drupal/apigee_edge": "^2.0",
        "drupal/apigee_m10n": "^2",

**Comment by shishir-intelli** [comment]
Hi @edpahang 
Could you please share with us the list of `composer show` output to investigate more on this issue. 
(_Run command `composer show`_)

Meantime, could you run `/update.php` and make sure everything is updated and there are no pending updates.

**Comment by edpahang** [comment]
Hi @shishir-intelli,
We appreciate you checking on this issue.  I'm attaching screenshots of the list -
![Screen Shot 2022-08-18 at 8 24 49 AM](https://user-images.githubusercontent.com/59853325/18543562
![Screen Shot 2022-08-18 at 8 25 36 AM](https://user-images.githubusercontent.com/59853325/185435657
![Screen Shot 2022-08-18 at 8 26 03 AM](https://user-images.githubusercontent.com/59853325/185435689-2a7c5081-80b2-4473-a9b2-34bbdcc13ba2.png)
![Screen Shot 2022-08-18 at 8 26 29 AM](https://user-images.githubusercontent.com/59853325/185435708-f97dfd45-ead1-492b-b529-4ad41d41882e.png)

-490357aa-6fc1-44fa-a748-f5c8fdf3d72f.png)
![Screen Shot 2022-08-18 at 8 27 08 AM](https://user-images.githubusercontent.com/59853325/185435744-7894db1f-b6e9-4f31-a388-5d9303583ca8.png)

7-3ee10b0f-84f0-49e9-827b-5a3838a4c419.png)

**Comment by edpahang** [comment]
I also did a - $ drush updb -y  with no pending updates.  And please let me know if you need anything else to investigate the issue.

**Comment by edpahang** [comment]
![Screen Shot 2022-08-18 at 8 24 49 AM](https://user-images.githubusercontent.com/59853325/185458257-9a3540b1-3bf4-4b09-980a-db7d1acac7ec.png)

**Comment by edpahang** [comment]
![Screen Shot 2022-08-18 at 8 27 08 AM](https://user-images.githubusercontent.com/59853325/185458355-2169e36f-b709-4153-b212-e00fa5ef0ab0.png)

**Comment by edpahang** [comment]
Added the screenshots that were not loaded properly the first time.

**Comment by shishir-intelli** [comment]
Hi @edpahang ,
The above `composer show` screenshot is a bit confusing and Drupal core is also missing there, 
Could you please run the command `Composer show` and from the terminal copy the entire list and paste it here which can be helpful to check the versions.

**Comment by shishir-intelli** [comment]
Just to make sure the api catalogs `View` exists, please go to `/admin/structure/views/view/apigee_api_catalog` and check if you can see this view as machine name `page_1`

**Comment by edpahang** [comment]
Hi @shishir-intelli - Here is a screenshot.  Both the API Catalog & API Catalog Admin has the Display name of page
![Screen Shot 2022-08-22 at 6 47 31 AM](https://user-images.githubusercontent.com/59853325/185937014-482ec193-4e00-47a5-ae62-28a6761778b0.png)
e

**Comment by shishir-intelli** [comment]
@edpahang 
Seems like the Views machine name has changed.
Could you edit the `API Catalog`(_Machine name `apigee_api_catalog`_) View and check if the machine name has changed. 
The machine name should `page_1`

Screenshot of `API Catalog`(_Machine name apigee_api_catalog_) View 
![Screenshot 2022-08-22 7 38 16 PM](https://user-images.githubusercontent.com/75600200/185941999-4aa4df9d-baad-4721-b6a3-416c304b7003.png)

 If the machine name has changed, then please change it back to `page_1` then flush all cache on drupal and try editing the content.

**Comment by edpahang** [comment]
Thanks @shishir-intelli for the update.  Looks like we have page_3 for the API Catalog (see screenshot) and page_1 for the API Catalog Admin.  I will try to edit and switch the pages.
![Screen Shot 2022-08-22 at 7 28 08 AM](https://user-images.githubusercontent.com/59853325/185948331-490722f7-30f7-4362-a951-4a6e9bbec981.png)

**Comment by shishir-intelli** [comment]
Yes, just change the machine name to `page_1` instead of `page_3` for `API Catalog` View and it will work fine.

Closing this issue for now, feel free to re-open it if you need any further help.
