### ISSUE TITLE
ApiDocAccessControlHandler.php uses invalid permission.

### ISSUE THREAD

**Issue by dpagini** [apigee/apigee-api-catalog-drupal#231]
## Description

This is not a valid permission...
https://github.com/apigee/apigee-api-catalog-drupal/blob/33d1aa2a0ea613b3bacd723b5ffdfe89bd539a74/src/Entity/Access/ApiDocAccessControlHandler.php#L88

It looks to me like at one point, `apidoc` was a custom entity, but that seems like it was changed to a node. 

## Actual Behavior
What happened after the steps to reproduce.

## Version Info
Drupal 10
Module `3.0.4`

**Comment by shishir-intelli** [comment]
@dpagini ,
Thank you for addressing this issue, We will certainly investigate it.

**Comment by shishir-intelli** [comment]
@dpagini 
The custom `apidoc` entity is deprecated so it will be removed in the next release.
see https://github.com/apigee/apigee-api-catalog-drupal/pull/84

**Comment by dpagini** [comment]
I'm using `3.x` already in my project... it seems to me the `apidoc` entity was removed a long time ago. The issue is that you're still using an "entity" permission in the above referenced file, and not the **new** "node permission". Does that make sense?

**Comment by shishir-intelli** [comment]
Correct, custom `apidoc` entity was removed long back however, there are still a few deprecated `apidoc` files present in 3x which are removed in this PR https://github.com/apigee/apigee-api-catalog-drupal/pull/233
Please use node `apidoc`. see https://github.com/apigee/apigee-api-catalog-drupal/pull/84
