### ISSUE TITLE
Sends null for XML and SOAP payloads

### ISSUE THREAD

**Issue by natesh245** [apigee/apigee-api-catalog-drupal#235]
Trying a xml or SOAP api from the api doc sends a null in the request payload

**Comment by natesh245** [comment]
XML and SOAP request payloads are not supported. The Api doc sends null body in the request

**Comment by shishir-intelli** [comment]
@natesh245 ,
Could you share us the steps to reproduce this issue.

**Comment by natesh245** [comment]
@shishir-intelli  we have defined a example request body for a soap api. It is showing up in swagger ui and is working as expected. In Drupal api doc this example soap payload is not showing and it is taking it as null when we invoke the api

**Comment by natesh245** [comment]
@shishir-intelli  we also have another api where we are sending a xml payload in the request url. This payload is not showing up in drupal api doc, but the same is working in swagger ui

**Comment by shishir-intelli** [comment]
Yes correct.
In Drupal, currently Smartdocs is used for API documentation solutions and there are few known issues. As of now, we do not have ETA to fix this issue.

I would suggest you install and use Swagger UI for API documentation in Drupal,

- https://github.com/apigee/apigee-api-catalog-drupal#:~:text=using%20Swagger%20UI%3A-,Install,-and%20enable%20the
- https://www.drupal.org/project/swagger_ui_formatter

**Comment by natesh245** [comment]
> Yes correct. In Drupal, currently Smartdocs is used for API documentation solutions and there are few known issues. As of now, we do not have ETA to fix this issue.
> 
> I would suggest you install and use Swagger UI for API documentation in Drupal,
> 
> * https://github.com/apigee/apigee-api-catalog-drupal#:~:text=using%20Swagger%20UI%3A-,Install,-and%20enable%20the
> * https://www.drupal.org/project/swagger_ui_formatter

@shishir-intelli thanks for the suggestion. We will try it out

**Comment by shishir-intelli** [comment]
Closing this issue, Feel free to reopen for any further help.
