### ISSUE TITLE
Search box functionality was not working in Developer portal

### ISSUE THREAD

**Issue by satishmsd598** [apigee/apigee-api-catalog-drupal#240]
We have installed Drupal 9 developer portal setup in Linux server and we have uploaded Open API Specs in dev portal successfully.

Our query, search box functionality was not working if we given any input in search box in developer portal and it shows 404 error code.

Please find below attached error screenshot.
Please 
![Dev Protal error screenshot](https://github.com/apigee/apigee-api-catalog-drupal/assets/152374738/6d7bf2df-2e00-4f65-bc0a-5668cf563a4a)

**Comment by satishmsd598** [comment]
Hi team,

We are not able to open any Open API specs document and we all  are getting 404 not found error.
while troubleshooting we are not able to access developer portal main page, we are getting below error,
![404 error](https://github.com/apigee/apigee-api-catalog-drupal/assets/152374738/e115051e-3229-44bf-8312-bee06dfe1d7f)

**Comment by shishir-intelli** [comment]
@satishmsd598 
In search `Advanced search' setting did you configured the `/apilist` page to search OpenAPI?

**Comment by shishir-intelli** [comment]
> Hi team,
> 
> We are not able to open any Open API specs document and we all are getting 404 not found error. while troubleshooting we are not able to access developer portal main page, we are getting below error, ![404 error](https://private-user-images.githubusercontent.com/152374738/286576149-e115051e-3229-44bf-8312-bee06dfe1d7f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjAwNDUsIm5iZiI6MTcwMTMxOTc0NSwicGF0aCI6Ii8xNTIzNzQ3MzgvMjg2NTc2MTQ5LWUxMTUwNTFlLTMyMjktNDRiZi04MzEyLWJlZTA2ZGZlMWQ3Zi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQwNDQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODFlNTZlMzk2Y2ZmZmI5ZWU3NTFjMWRlOTJjYWNjZTk4MGM5OGE1Yzk1OTc2MjY4ZWIyYWU3MmY2ZmJhYmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I6i1ViyQJNe6PyYtkDTI5KPa1qzcL3ublfb39P3Xv1M)

Can you please share the sceenshot of `/admin/structure/types/manage/apidoc/display' to verify the format for OpenAPI specification field selected.

Also, please could you share us the result list of command: `composer show`.

**Comment by satishmolina** [comment]
> @satishmsd598 In search `Advanced search' setting did you configured the `/apilist` page to search OpenAPI?

Yes

**Comment by satishmolina** [comment]
> /admin/structure/types/manage/apidoc/
While troubleshooting we are not able to access developer portal main page.

I have attached composer show command output.
![Composer command output](https://github.com/apigee/apigee-api-catalog-drupal/assets/152472204/31fa8103-f94f-45df-ba29-255cd2a6306e)

**Comment by shishir-intelli** [comment]
You are in wrong directory. cd to your project directory then run `composer show`.

**Comment by satishmolina** [comment]
Please find below attachments of compose show.

![Composer ouput1](https://github.com/apigee/apigee-api-catalog-drupal/assets/152472204/4285b68d-805f-47db-8ece-f0526cc21c34)
![Composer ouput2](https://github.com/apigee/apigee-api-catalog-drupal/assets/152472204/3e98a1dc-e1ce-4cab-acb9-38b910a86e55)
![Composer ouput3](https://github.com/apigee/apigee-api-catalog-drupal/assets/152472204/a1a3e3e8-aceb-406b-b9bd-54fd32a0c101)
![Composer ouput4](https://github.com/apigee/apigee-api-catalog-drupal/assets/152472204/90c0c915-0257-4dd6-83bc-2b4a97d5cb8a)
![Composer ouput5](https://github.com/apigee/apigee-api-catalog-drupal/assets/152472204/6a75cd50-0932-4bfa-b48b-4b6d3947fb9e)

**Comment by shishir-intelli** [comment]
Could you also please share us the screenshot of `/admin/structure/types/manage/apidoc/display` to verify the format for OpenAPI specification field selected.

**Comment by satishmolina** [comment]
We can't share the screenshot of /admin/structure/types/manage/apidoc/display because we are not able to access developer portal main page, it shows 404 error page,

**Comment by shishir-intelli** [comment]
Is your nginx configured correctly to work with Drupal?
Check this https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/ especially `try_files` and `@rewrite`
or 
see this https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud#:~:text=cnf%C2%A0file.-,Install,-an%20Nginx%20web

**Comment by satishmolina** [comment]
could you please schedule a call to work on this issue?

**Comment by shishir-intelli** [comment]
@satishmolina ,
As per our conversation over call, the above issue's seem to be nginx server configuration not as per the document, 
kindly configure your nginx server settings in line with our established standards.
https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud#s-install-an-nginx-web-server

Closing this issue for now, feel free to re-open for any further help.
