### ISSUE TITLE
date-time rendering issue

### ISSUE THREAD

**Issue by Akashr7n** [apigee/apigee-api-catalog-drupal#241]
## Description
When publishing API in yaml, if any field has value transDateTime: 2020-12-18T22:01:06 (value is unquoted), it is rendered as {}. refer screenshot.

swagger editor online and many other tools render quoted value.

## Steps to Reproduce
Upload a openapi spec in yaml with example/value for any property as 2020-12-18T22:01:06

## Actual Behavior
{} is rendered.

## Expected Behavior
"2020-12-18T22:01:06" is expected

## Screenshots
<img width="209" alt="image" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/23741713/5f4bff53-57bd-49b0-8385-1ddf4a73c247">

## Notes
NA

## Version Info
core - 9.3.12
Apigee API Catalog - 3.0.5

**Comment by shishir-intelli** [comment]
@Akashr7n 
The current UI formatter used is `smartdocs`. There are few known issues in `smartdoc` library , However we do not have ETA to fix this.

You can checkout other third party UI formatter for the field such as Swagger UI https://www.drupal.org/docs/8/modules/apigee-api-catalog/customize-your-api-catalog#s-displayopenapi-specs-using-other-rendering-formats

**Comment by Akashr7n** [comment]
@shishir-intelli Thanks for the suggestion.
Is it possible to update only the swagger-ui library to latest([v5.10.5](https://github.com/swagger-api/swagger-ui/releases/tag/v5.10.5)) with 'Swagger UI Field Formatter' version 8.x-3.3

currently swagger-ui library version is 4.1.3

**Comment by shishir-intelli** [comment]
@Akashr7n 
`Swagger UI Field Formatter` is a third party Drupal module and not managed by us, 
you can check the documentation for `Swagger UI Field Formatter` [here](https://www.drupal.org/project/swagger_ui_formatter)

**Comment by shishir-intelli** [comment]
Closing this issue for now, feel free to reopen for any further help.

**Comment by Akashr7n** [comment]
Updated swagger-ui library to latest([v5.10.5](https://github.com/swagger-api/swagger-ui/releases/tag/v5.10.5)) with 'Swagger UI Field Formatter' version 8.x-3.3

working fine for us. Thanks for the support.
