### ISSUE TITLE
Support of GraphQL Service in Apigee Edge for Private Cloud

### ISSUE THREAD

**Issue by manojitha** [apigee/apigee-api-catalog-drupal#244]
## Description
We are using Apigee Edge for Private Cloud and we are trying to expose the GraphQL Services but we were not able to see any GraphQL Policy to add which is available in Hybrid.

## Expected Behavior
We would like to have same GraphQL policy in Apigee Edge for Private Cloud similar to Hybrid.

[Using GraphQL - Hybrid](https://cloud.google.com/apigee/docs/api-platform/develop/graphql)

## Notes
We are trying to expose the GraphQL Service in the Developer Portal and were not able to have different graphQL service endpoint for different GraphQL services.

**Comment by kedarkhaire** [comment]
Hi @manojitha 

Adding my understanding below for your request

- After the Developer portal setup,  enable the _GraphQL for Apigee_ module.
- Create GraphQL Doc from `/node/add/graphql_doc`, Add the required details and specification in a schema graphql file/ endpoint url
-  For different graphQL service endpoint, we need to create different GraphQL docs

Regarding the Graphql Policy, I am not sure about the request, can you please share the screenshot for your requirement, with comments and points to understand.

Thanks!

**Comment by giteshk** [comment]
@manojitha,

GraphQL policies are not available in Apigee Edge for Private cloud (OPDK). Please talk to Apigee Support for any details regarding runtime policies.

As far as publishing graphQL endpoints on Developer portal, You should be able to publish multiple catalog items for your different GraphQL endpoints.

**Comment by kedarkhaire** [comment]
Closing the issue, seems the above comment helped you, if not, please feel free to reopen the ticket with the required details.
Thanks!
