### ISSUE TITLE
"apidoc" entity type problem after upgrade to drupal 10.1

### ISSUE THREAD

**Issue by inbalj** [apigee/apigee-api-catalog-drupal#246]
I have upgraded a Drupal 9.3 site (with Apigee kickstart distribution) to Drupal 10.1 and Apigee kickstart 3.0 (from 2.0) 
I keep getting when using drush **the error** - The "apidoc" entity type does not exist. 
Or  **the warning** - Undefined array key "apidoc" ContentModerationRouteSubscriber.php:95

another issue that may be connected is -
A custom view based on Apigee API Catalog that throws the following warning: Undefined array key "id" in Drupal\views\Plugin\views\display\DisplayPluginBase ->getHandlers() (line 875)
There is no "id" as a field in the view.

## Screenshots
![WhatsApp Image 2024-02-28 at 11 46 46](https://github.com/apigee/apigee-api-catalog-drupal/assets/8232597/5b2277fa-b903-45b9-b53d-00550dd08f9f)

## Version Info
drupal: 10.1.8
php: 8.1.26
drush: 11.6
apigee api catalog: 3.0.5
apigee is running on private cloud

**Comment by kedarkhaire** [comment]
Hi @inbalj 
Thanks for sharing the issue, we will look into it,
Can you please share few details to us,

- Complete error log related to the issue.
- Steps you took to migrate from D9 to D10 with version specifics
- Also did you follow the [document for migration](https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/upgrade-from-drupal-9-to-drupal-10)

It will be quite helpful to us if you share the above details.
Thanks!

**Comment by inbalj** [comment]
Hi @kedarkhaire , 
Thank you for looking into this issue. Unfortunately, I can't share the logs, since my environment are in closed environment. 
I'm attaching below my steps to migrate from D9 to D10:

Upgrading to D10
================
Custom Modules
--------------
change core_version_requirement: ^8 || ^9 || ^10
 
CKEditor
--------
install ckeditor 5
uninstall codesnippet ,ckeditor_font, panelbutton, colorbutton
uninstall url_redirect
 
go to
/admin/config/content/formats
change from ckeditor to ckeditor 5 in basic and full html
In full html configuraion disable style button from active toolbar
  
 
THEMES
------
go to
/admin/appearance
install claro , olivero
uninstall bartik , seven
 
drush cr
drush updb
/admin/config/development/configuration/full/export
 

copy files from vendor core, libraries, profile,
copy fontawesome to libraries
 
go to
/admin/config/development/performance
disable aggregation to css and js
clear cache
enable aggregation to css and js
 
rebuild permissions
 
Modules
-------
 uninstall/disable CKEditor 4
install url_redirect
install jQuery UI Draggable

 
go to
/admin/structure/views/view/apigee_api_catalog/edit/block_apis
 
remove API Style
 
 
go to
/admin/structure/views/view/apigee_api_catalog/edit/block_apis
in Advanced
change to Use AJAX: No
 
go to
/var/www/xxxxx/config/system/url_redirect
add Role
copy file apigee_kickstart_customizer.apigee_kickstart.css
to/var/www/xxxxx/web/sites/default/files
 
disable all the libraries (/admin/structure/webform/config/libraries)

Regarding the last point, I did read the documentation  you refered to ... still got problems....
I would appreciate your help...

**Comment by kedarkhaire** [comment]
Hi @inbalj 

Whenever we plan to migrate, we upgrade our site to it's minor's latest version i.e. instead of 9.3 it should be upgraded latest version of ^9.5 & then we try to migrate to it's major's latest version i.e. ^10.

First try to upgrade D9.3 to 9.5, run the update script and clear the cache. Check for any errors.
If all is good then migrate to ^10, run update script follow the points you mentioned and clear cache and then check for any errors.

I see you may have missed this ^^ step.

I checked with migration from D9.5 to D10 I don't see errors related to the module. Can you please follow the migration again with the above point I mentioned, if after that the issue arise, we can look into it, but do provide a detailed log of it. It helps us to know the issue.

Thanks!

**Comment by kedarkhaire** [comment]
Also are your custom modules linked to the Apigee Api Catlog  module ?

**Comment by inbalj** [comment]
I'm upgraded from 9.5 and I'm using custom modules. I changed the custom modules so they will work with D10. Some of my custom modules are either overriding the Apigee Api Catlog or extending capabilities based on it.

**Comment by kedarkhaire** [comment]
Hi @inbalj 

Seems, your custom module is creating this issue. Can you try uninstalling those modules and check the migration process again ?

Thanks!

**Comment by inbalj** [comment]
@kedarkhaire 
Thank you for your reply. I'll check it out and let you know.

**Comment by kedarkhaire** [comment]
Hi @inbalj 
Its been more than a month there is no response, considering, last comment was helpful to solve the issue.
Closing this ticket for now.
Thanks!
