### ISSUE TITLE
Apigee Developer portal kickstart specs does not render on very first click on view documentation.

### ISSUE THREAD

**Issue by ashishkumar16osttra** [apigee/apigee-api-catalog-drupal#256]
## Description

Deployed Apigee Developer portal kickstart solution on GCP.
Once the setup got ready. I explored few pre existing API Catalog.
The api specs not getting rendered on very first click on View Documentation. but I have to reload the page to work.
I suspect this is with the NGINX server as in my local machine when I use Apache server there is not such issue.

## Steps to Reproduce
1. Open Incognito window
2. Launch the developer portal website.
3. Click on View Documentation.

## Actual Behavior
It shows a page with empty spec 

## Expected Behavior
It must list all the apis od spec

## Screenshots
<img width="868" alt="image" src="https://github.com/apigee/apigee-api-catalog-drupal/assets/131158094/b8958e97-1814-4a88-8860-55752777d2cd">

## Notes
Seems the issue is reproducible with NGINX server not with Apache.

## Version Info
Apigee developer portal kickstart (10.1.8)
NGINX(1.22.1)
Drupal(10.1.x)
MySQL-Client(15.1)
PHP(8.2.7)
Ops Agent(2.35.0)
OS: Debian (12)

**Comment by kedarkhaire** [comment]
Hi @ashishkumar16osttra 
Thanks for mentioning, we will look into this issue.

**Comment by kedarkhaire** [comment]
Hi @ashishkumar16osttra 
As per your other post on community, you were facing issue on input field not visible, and this one. This can be a issue with current formatter.
Try using other field formatters, here are the examples - https://github.com/apigee/apigee-api-catalog-drupal/blob/3.x/README.md#overview
Do let us know, if this change of formatter works for both of the issue.
Thanks!

**Comment by kedarkhaire** [comment]
Considering the above solution worked for you, as there is not reply from past 2 weeks, anyways, if any issue faced related to it, feel free to reopen the issue.
Thanks!
