### ISSUE TITLE
Api Spec (API Reference/resourcePath/schema) under API Catalog on Drupal Developer portal loading intermittently

### ISSUE THREAD

**Issue by anoopgoel** [apigee/apigee-api-catalog-drupal#259]
## Description
Api Spec (API Reference/resourcePath/schema) under API Catalog on Drupal Developer portal loading intermittently. Api spec loading on refreshing the page else API reference is coming blank.

Same issue seems reported by someone here: https://www.googlecloudcommunity.com/gc/Apigee/Apigee-Developer-portal-kickstart-specs-does-not-render-on-very/m-p/786059#M80087

## Steps to Reproduce
1. Go to 'Drupal portal/apis'
2. Click on 'View Documentation' under API Catalog
3. Resource types are blank and loads after refreshing the page.

## Actual Behavior
Resource types are blank and loads after refreshing the page.

## Expected Behavior
Resource types should not be blank and show resources (resoucePath/schema)

## Screenshots
Screenshot attached.
<img width="743" alt="Api-spec-blank" src="https://github.com/user-attachments/assets/29ffd414-8b81-4cfc-9cf1-ff874378ef46">

**Comment by kedarkhaire** [comment]
Hi @anoopgoel 

This can be the issue with formatter you are currently using, try using other formatter as mentioned [here](https://github.com/apigee/apigee-api-catalog-drupal/blob/3.x/README.md#overview).

The above change will solve your issue. Do let us know, if any other issue you faced related to this or it works for you.

Thanks!

**Comment by anoopgoel** [comment]
Hi @kedarkhaire 

Thanks for your response. Yes it resolved my issue.

Thanks again!
Anoop Goel
