### ISSUE TITLE
Add "Try it now" functionality

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#29]

**Comment by d1ndra** [comment]
Hi @cnovak is there an ETA on when this functionality will be available?

**Comment by arunz6161** [comment]
Hi @d1ndra - thanks for your interest in "Try it now" functionality. We are planning on making this feature available as part of our next release in 07/2019.

**Comment by d1ndra** [comment]
Thanks @arunz6161. Is there a beta/dev release we can work with to check/build on this feature before your release in 07/2019?

**Comment by earth2marsh** [comment]
We'll reference issue #29 when there is anything that addresses it.

**Comment by arunz6161** [comment]
@d1ndra wanted to let you know that we are running behind schedule here. This story has been scheduled for the current sprint, however we will know more about the ETA by end of this sprint ( 2 weeks from now). I will update this issue then.
