### ISSUE TITLE
Add an API Response mocking system for use with API Products.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-api-catalog-drupal#31]
**Is your feature request related to a problem? Please describe.**
There will be some tests that will require Apigee Edge API Products are available. We need a way to mock these objects like what's available in the `apigee_m10n` module to test related functionality.

https://github.com/apigee/apigee-edge-drupal/pull/79 proposes to move the mocking system that is used in the `apigee_m10n` module into the `apigee_edge` module which would satisfy our needs.

We could work on that PR or alternatively create a new dev only project that would accomplish the same thing and could be used by any module.

**Comment by cnovak** [comment]
We no longer have any association to API Products in this module, so will close this issue.
