### ISSUE TITLE
APIDoc field "name" is too short

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#38]
**Is your feature request related to a problem? Please describe.**
We have specs with a name more than 50 chars, however the BaseFieldDefinition for field name has the setting max_length 50 characters (ergo the db field length to 50 chars also).

**Describe the solution you'd like**
Change field to be 255 chars.

## Steps to reproduce
1. Enabled API Catalog module
2. Create API Doc with a name larger than 50 chars
3. The field will be truncated to 50 chars.

Source: https://community.apigee.com/questions/69668/drupal-8-apidoc-field-name-has-max-length-of-50-ch.html

**Comment by jmburnz** [comment]
In our case we get an exception because we're publishing via rest api and parsing the title field out the swagger - I could truncate it but those are business decisions above my pay grade :)

**Comment by jacine** [comment]
HI @jmburnz!!! 👋👋👋

**Comment by jmburnz** [comment]
> HI @jmburnz!!! 👋👋👋

Wow, hi @jacine, long time no see 😄 👋
