### ISSUE TITLE
Expose REST APIs to update API Docs

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#40]
**Is your feature request related to a problem? Please describe.**
How do I automate the publishing API docs in the API catalog module?  

**Describe the solution you'd like**
Document explaining how to get the API Catalog publishing/creation exposed as an API

**Describe alternatives you've considered**
A way this can be set up automagically

**Additional context**
I  <3 APIs

**Comment by jbennett13** [comment]
This is now published at https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs.  Feel free to edit - just wanted to make it available ASAP.

**Comment by cnovak** [comment]
Thanks @jbennett13 will close this ticket.
