### ISSUE TITLE
Render WSDL for live testing of SOAP APIs

### ISSUE THREAD

**Issue by kford** [apigee/apigee-api-catalog-drupal#54]
**Is your feature request related to a problem? Please describe.**
I have SOAP APIs, I need them to be testable in the portal

**Describe the solution you'd like**
Something like SmartDocs for WSDL -- here is a module for Drupal 7 with try-it-now: https://www.drupal.org/project/wsdl_docs

**Describe alternatives you've considered**
do nothing - Put the WSDL file on the site, and users can download and use client of their choice

**Additional context**

**Comment by kscheirer** [comment]
I think the main issue is that wsdl_docs is built on top of https://www.drupal.org/project/wsclient, which didn't make the leap to D8. 

Another question to consider: wsdl_docs parses the file and makes individual content entities (like smartdocs did in d7). However the D8 version of smartdocs uses js to render the whole openapi doc at once at display time, its no longer creating individual nodes.

**Comment by cnovak** [comment]
We are not planning on adding WSDL support to the SmartDocs Angular application. The best bet is to use the [WSDL Docs Drupal module](https://www.drupal.org/project/wsdl_docs) which is now available for Drupal 8.
