### ISSUE TITLE
bulk import/uploads api docs

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-api-catalog-drupal#58]
Is there anyway to upload bulk import or upload json and yaml files.

**Comment by giteshk** [comment]
@rengan76 We have a maven plugin built to help with this.

https://github.com/apigee/apigee-smartdocs-maven-plugin/releases/tag/apigee-smartdocs-maven-plugin-2.0.0

**Comment by rengan76** [comment]
@giteshk thanks. I need to import in drupal 8 instead of adding doc by doc into a catalog. (it should add in apidoc table). i dont want to import in apigee for now.

**Comment by kscheirer** [comment]
That maven plugin does import into Drupal8. There is a separate maven plugin that imports into apigee edge.

**Comment by rengan76** [comment]
Thanks. Tried adding the url,username password but. keeps giving me this error
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by rengan76** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.925 s
[INFO] Finished at: 2019-12-05T20:10:41Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc failed: Update failure: 404 Not Found

**Comment by rengan76** [comment]
Can anyone say me wats that error. how do i fix it

**Comment by giteshk** [comment]
Did you finish the steps listed under https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs#s-prerequisites

**Comment by rengan76** [comment]
now i have added those 3 modules.  now i am getting this error
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc failed: Update failure: 400 Bad Request
{"jsonapi":{"version":"1.0",

**Comment by rengan76** [comment]
Thanks again. Finally after few hacks on the code of core files i am able to upload few hunder files. but few files i am not able to due to tab errors
[ERROR] Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc failed: while scanning for the next token
[ERROR] found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
[ERROR]  in 'reader', line 25, column 1:
[ERROR]                   "description": "OK"
[ERROR]     ^
[ERROR]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.0.0:apidoc failed: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 25, column 1:
                  "description": "OK"

**Comment by cnovak** [comment]
Can you send us info on what you changed or submit a PR so we can fix this issue or update the documentation?

**Comment by cnovak** [comment]
If you are having issues with the SmartDocs Maven project, can you add an issue into that project's issue queue? https://github.com/apigee/apigee-smartdocs-maven-plugin/issues.  Will close this since it is not part of this project.
