### ISSUE TITLE
jsonAPI apicatalog - file

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-api-catalog-drupal#61]
{
	"data": {
	    "type": "apidoc--apidoc",
	    "attributes": {
	      "status": true,
	      "name": "New API Doc",
	      "description": {
	        "value": "<p>Lorem ipsum...</p>",
	        "format": "basic_html"
	      },
	      "spec_file_source": "file",
		      "relationships": {
			       "spec": {
			         "data": {
			           "type": "file--file",
			           "id": "{{file_a074bcb8-3bd4-476a-854a-2e13078bf668}}"
			         }
			       }
    			}
	    }
	}
}
tried to update uuid still nothing is showing up on the admin apicatalog. file is not there. 
As per documentation. first uploaded file parsed the uuid and applied on other api call. after i got 201 response. i dont see the file linked. what is that i am missing

**Comment by connorpwilliams** [comment]
Following along here, we made some changes to the json object to correct a few minor mistakes. API Doc still gets created but also no api spec file was linked. Not sure where I can troubleshoot this from.

**Comment by rengan76** [comment]
some can provide us the json:api documenation

**Comment by cnovak** [comment]
I am not sure if I understand the steps to reproduce this issue.  Can you give more details on:
1. What document you are following
2. The step you are seeing an issue on
3. Any useful info such as a test file that causes the issue

**Comment by arunz6161** [comment]
@rengan76 are you trying the follow the steps provided at :  https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs#s-option-b-create-a-new-api-doc-and-uploading-the-spec-file ?

Also are you seeing this issue with a specific spec ? Can you try using the petstore spec attached below ?

Also, moving forward- please provide all the details as the bug template suggests. 

[swagger.yaml.zip](https://github.com/apigee/apigee-api-catalog-drupal/files/3957259/swagger.yaml.zip)

**Comment by rengan76** [comment]
@arunz6161  thanks. 

This is what i tried
1. first upload the file this is the response i got

    [data] => stdClass Object
        (
            [type] => file--file
            [id] => 07cf5bd6-f504-4ad4-b010-9fe6955a77e0
            [attributes] => stdClass Object
                (
                    [drupal_internal__fid] => 804
                )

            [links] => stdClass Object
                (
                    [self] => stdClass Object
                        (
                            [href] => https://XXXXXX/jsonapi/file/file/07cf5bd6-f504-4ad4-b010-9fe6955a77e0
                        )

                )

        )

    [links] => stdClass Object
        (
            [self] => stdClass Object
                (
                    [href] => https://xxxxxx/jsonapi/file/file/07cf5bd6-f504-4ad4-b010-9fe6955a77e0
                )

        )

)

2. When try get that UUID and post it again

{
	"data": {
	    "type": "apidoc--apidoc",
	    "attributes": {
	      "status": true,
	      "name": "dec12 testing doc",
	      "description": {
	        "value": "<p>Lorem ipsum...</p>",
	        "format": "basic_html"
	      },
	      "spec_file_source": "file"
	    },
		      "relationships": {
			       "spec": {
			         "data": {
			           "type": "file--file",
			           "id":  "07cf5bd6-f504-4ad4-b010-9fe6955a77e0"
			         }
			       }
    			}
	}
}

Only the doc is getting created no file linked. 
Also i tested on the db i am seeing spec and spec_md5 and spec_target_id not created

**Comment by rengan76** [comment]
@arunz6161 Also one more thing file uploaded is storing always as temporary. its not permanent thats another bug

**Comment by arlina-espinoza** [comment]
@rengan76 It is expected that the file be marked temporary until it is used in a reference, otherwise it will be automatically deleted during the next cron run (see https://www.drupal.org/node/3024331).
Also, could you please tell us what the second API call returns (HTTP status and data).

**Comment by rengan76** [comment]
```
{
    "jsonapi": {
        "version": "1.0",
        "meta": {
            "links": {
                "self": {
                    "href": "http://jsonapi.org/format/1.0/"
                }
            }
        }
    },
    "data": {
        "type": "apidoc--apidoc",
        "id": "0ccfcc53-0d80-4915-9440-df61373bc07e",
        "attributes": {
            "drupal_internal__id": 154,
            "drupal_internal__revision_id": 322,
            "name": "dec12 testing doc"
        },
        "links": {
            "self": {
                "href": "https://XXXXXXXx/jsonapi/apidoc/apidoc/0ccfcc53-0d80-4915-9440-df61373bc07e"
            }
        }
    },
    "links": {
        "self": {
            "href": "https://XXXXXX/jsonapi/apidoc/apidoc"
        }
    }
}
```

**Comment by rengan76** [comment]
Can anyone send me the postman collections

**Comment by rengan76** [comment]
I have also tried file link url
```
{
  "data": {
    "type": "apidoc--apidoc",
    "attributes": {
      "status": true,
      "name": "New API Doc with URL 2",
      "description": {
        "value": "<p>Lorem ipsu URL m...</p>",
        "format": "basic_html"
      },
      "spec_file_source": "url",
      "file_link": {
        "uri": "https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml"
      }
    }
  }
}
```

its getitng 201 and doc created but no url selected.  Something wrong.

**Comment by arlina-espinoza** [comment]
@rengan76 Here is an unofficial postman collection that I created for testing: https://documenter.getpostman.com/view/550470/S1a1aoeF

If you are still getting fails, could you provide us with more details? Versions of Drupal core, module, PHP, authentication method, etc.

**Comment by kscheirer** [comment]
Can you post the code you're using to do this?

**Comment by thecpdubguy** [comment]
I do not have the file creation code @rengan76  used, but have seen that a file uuid gets generated. Below is the post body we are using to create an API Doc to the url path `/jsonapi/apidoc/apidoc` using a POST request

```json
{
    "data": {
        "type": "apidoc--apidoc",
        "attributes": {
            "status": true,
            "name": "Test spec upload",
            "description": {
                "value": "<p>Lorem ipsum...</p>",
                "format": "basic_html"
            },
            "spec_file_source": "file"
        },
        "relationships": {
            "spec": {
                "data": {
                    "type": "file--file",
                    "id": "96c8deef-8c87-492c-9a33-b3e8a7c60585"
                }
            }
        }
    }
}
```

I can also confirm that the data we get back in the response is much smaller than what was in @arlina-espinoza 's link for "POST Create a new API Doc with uploaded file spec - Step 2: API Doc". Again, rengan76 will have that response body. I will have him double check the request against the postman sample provided above.

**Comment by rengan76** [comment]
```php

<?php
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://xxxxxxx/jsonapi/apidoc/apidoc/spec');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$post = array(
    'file' => '@' .realpath('/app/apigee-smartdocs/samples/Drupal8/DevPortal/specs/xxx.yaml')
);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

$headers = array();
$headers[] = 'Accept: application/vnd.api+json';
$headers[] = 'Authorization: Basic xxxxxxx==';
$headers[] = 'Content-Disposition: file; filename="xxxxx.yaml"';
$headers[] = 'Content-Type: application/octet-stream';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$result = curl_exec($ch);
$res = json_decode($result);
print_r($res);
$uuid = $res->data->id;
echo $uuid;

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

```

**Comment by connorpwilliams** [comment]
Creating the proper bug report as per bug_report issue template and bringing all info together here, sorry for posting this late.

**Describe the bug**
When using the json api to upload and create an api spec, file gets created with uuid. When using uuid to create spec via curl request, response code is 201 but when viewing api doc in api catalog on /admin page, there is no spec linked.

**To Reproduce**
Steps to reproduce the behavior:
1. Following [this link](https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs#s-option-b-create-a-new-api-doc-and-uploading-the-spec-file documentation)
2. Execute curl request to create file
3. Get UUID from response
4. Execute curl request to create api spec
5. Check api catalog for api spec, record is created but no spec is linked.

**Expected behavior**
File is uploaded and linked in created api spec

**Screenshots**
N/A

**Additional context**
I've seen working requests and followed samples but no success

**Version Info**
Drupal 8.7.3
PHP Version 7.2.22
MySQL 8.0.16

**Data**
## File Creation
### Request
```bash
curl --location --request POST "https://xxxxxxx/jsonapi/apidoc/apidoc/spec" \
--header "Accept: application/vnd.api+json" \
--header "Authorization: Basic xxxxxx" \
--header "Content-Type: application/octet-stream" \
--header "Content-Disposition: file; filename=\"xxxxxx.yaml\"" \
--insecure \
--data "@/app/apigee-smartdocs/samples/Drupal8/DevPortal/specs/xxxxxx.yaml"
```

### Response
```json
{
    "jsonapi": {
        "version": "1.0",
        "meta": {
            "links": {
                "self": {
                    "href": "http://jsonapi.org/format/1.0/"
                }
            }
        }
    },
    "data": {
        "type": "file--file",
        "id": "xxxxxx",
        "attributes": {
            "drupal_internal__fid": 822
        },
        "links": {
            "self": {
                "href": "https://xxxxxx/jsonapi/file/file/xxxxxx"
            }
        }
    },
    "links": {
        "self": {
            "href": "https://xxxxxx/jsonapi/file/file/xxxxxx"
        }
    }
}
```

## Spec Creation
### Request
```bash
curl --location --request POST "https://xxxxxxx/jsonapi/apidoc/apidoc" \
--header "Accept: application/vnd.api+json" \
--header "Authorization: Basic xxxxxx" \
--header "Content-Type: application/vnd.api+json" \
--insecure \
--data "{
  \"data\": {
    \"type\": \"apidoc--apidoc\",
    \"attributes\": {
      \"status\": true,
      \"name\": \"Connors New API Doc\",
      \"description\": {
        \"value\": \"<p>Lorem ipsum...</p>\",
        \"format\": \"basic_html\"
      },
      \"spec_file_source\": \"file\"
    },
    \"relationships\": {
      \"spec\": {
        \"data\": {
          \"type\": \"file--file\",
          \"id\": \"xxxxxx\"
        }
      }
    }
  }
}"
```

### Response
```json
{
    "jsonapi": {
        "version": "1.0",
        "meta": {
            "links": {
                "self": {
                    "href": "http://jsonapi.org/format/1.0/"
                }
            }
        }
    },
    "data": {
        "type": "apidoc--apidoc",
        "id": "xxxxxx",
        "attributes": {
            "drupal_internal__id": 171,
            "drupal_internal__revision_id": 341,
            "name": "New API Doc"
        },
        "links": {
            "self": {
                "href": "https://xxxxxx/jsonapi/apidoc/apidoc/xxxxxx"
            }
        }
    },
    "links": {
        "self": {
            "href": "https://xxxxxx/jsonapi/apidoc/apidoc"
        }
    }
}
```

**Comment by rengan76** [comment]
Finally i am able to upload with file contents. but i am seeing header footer of the file with this 
------------------------------160e8e59b66a
Content-Disposition: form-data; name="file" 

Why its appending that?

**Comment by arlina-espinoza** [comment]
> Finally i am able to upload with file contents. but i am seeing header footer of the file with this
> ------------------------------160e8e59b66a
> Content-Disposition: form-data; name="file"
> 
> Why its appending that?

Could you specify where are you seeing that @rengan76 ?

**Comment by connorpwilliams** [comment]
> > Finally i am able to upload with file contents. but i am seeing header footer of the file with this
> > ------------------------------160e8e59b66a
> > Content-Disposition: form-data; name="file"
> > Why its appending that?
> 
> Could you specify where are you seeing that @rengan76 ?

I think we were looking at the files uploaded by the first api call to create them after they were created on the server. The curl request I posted above was not working but rengen76 should have a PHP script that we can look at.

**Comment by rengan76** [comment]
@arlina-espinoza ,  it was my bad when i post the data it went with Array values 0 and file. Finally i figured out and fixed. Its all set.

**Comment by arlina-espinoza** [comment]
Great to hear! Closing issue.
