### ISSUE TITLE
Need support for SmartDocs Proxy

### ISSUE THREAD

**Issue by m-khan23** [apigee/apigee-api-catalog-drupal#63]
We need support for smartdocs proxy (that comes with the default validate org) similar to support in Drupal 7. Adding CORS support to each individual proxy is a nightmare - we are having to backtrack our changes. Thanks.

**Comment by arunz6161** [comment]
@m-khan23 thanks for logging your request. Support for smartdocs proxy will be a significant change and not something on the roadmap. However, on the edge side there are plans to make applying CORS easier. No ETA on that at the moment.

**Comment by m-khan23** [comment]
Thanks. A little disappointing but appreciate the response.
