### ISSUE TITLE
Contributing to this project

### ISSUE THREAD

**Issue by m-khan23** [apigee/apigee-api-catalog-drupal#65]
I'm kind of puzzled with this 'open source' project. Most of the core functionality and theming are hidden in:

https://www.gstatic.com/smartdocs/1.1.0/styles.css: 
https://www.gstatic.com/smartdocs/1.1.0/vendor.js

Furthermore, vendor is pretty obfuscated and even local changes are difficult. 

Would it make more sense to have obfuscated non minified styles, vendor, and other core functionality files in git so we can see changes and actually contribute? Otherwise, I don't foresee anyone actually able to contribute effectively. Thanks!

**Comment by cnovak** [comment]
Thanks for your interest in helping with our projects. 

However, the default OpenAPI spec renderer the API Catalog module uses is called SmartDocs, and is a separate Angular application that is not open source at this time.

**Comment by earth2marsh** [comment]
The catalog itself is a specific kind of content management problem that this module addresses, namely making API products available for discovery and adoption. It also provides the framework for rendering documentation from an OpenAPI spec, but it does not itself render that documentation. For convenience, we have included SmartDocs as a rendering option out of the box, but that is not an open source project today. If you prefer another rendering solution, such as Swagger UI, that is a valid approach.
