### ISSUE TITLE
SmartDocs: enum autocomplete does not work

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#67]
**Describe the bug**
When creating a spec that has an enum, the UI autocomplete does not work.

**To Reproduce**
1. Use spec [enum-autocomplete-test-oas2.yaml.txt](https://github.com/apigee/apigee-api-catalog-drupal/files/4037786/enum-autocomplete-test-oas2.yaml.txt) in API Catalog
2. Go to SmartDocs renderer to try API
3. Click on circle w/plus sign in body to add a value

**Expected behavior**
Nothing happens when clicking circle w/plus sign

**Screenshots**
<img width="619" alt="enum-error-screenshot" src="https://user-images.githubusercontent.com/613093/72024495-67389c80-322a-11ea-8ef6-cbbc38bb8227.png">

**Comment by arunz6161** [comment]
To validate if this issue was ever seen on IE portals.

**Comment by arunz6161** [comment]
Feature works as expected in IE portals.

<img width="433" alt="Screen Shot 2020-01-26 at 11 27 29 PM" src="https://user-images.githubusercontent.com/4381612/73156731-8db45f80-4093-11ea-9348-acba98bd5d97.png">

**Comment by raakesh-blokhra** [comment]
Closing this issue, added the config update as an internal goal, and will be treated as an enhancement. Please reopen if this still needs work.
