### ISSUE TITLE
Document how to add CORS in API Proxies to get SmartDocs to work correctly.

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-api-catalog-drupal#68]

**Comment by cnovak** [comment]
I gave this to @jbennett13 who is documenting this issue

**Comment by jbennett13** [comment]
Draft: 
 https://docs.google.com/document/d/1e3O3dZsk6DpR5kWHGxydhy69EBtqxSiLrg_bdCnQv8k/edit?usp=sharing

**Comment by jbennett13** [comment]
Added page in API Catalog docs:  https://www.drupal.org/docs/8/modules/apigee-api-catalog/use-smartdocs-with-apigee-edge
Linked to page from Apigee Edge:  https://www.drupal.org/docs/8/modules/apigee-edge/document-your-apis
Will integrate into docs.apigee.com where appropriate.

**Comment by cnovak** [comment]
@jbennett13 can you close this issue or is there more to do?
