### ISSUE TITLE
API Catalog page re-render issue

### ISSUE THREAD

**Issue by gautam-dac** [apigee/apigee-api-catalog-drupal#70]
When we load the API Catalog view page for the first time, it loads fine.
In the same browser, after we clear all the browsing data from browser and reload the API Catalog view page, it does not render.

We need to reload the page again to get the data.

Can someone suggest a solution for this ?

**Comment by dknezicd** [comment]
It's the ordering of the smartdocs libraries. This PR should resolve it https://github.com/apigee/apigee-api-catalog-drupal/pull/74

**Comment by SajithAthukorala** [comment]
@cnovak , @dknezicd  Thanks for the patch however we are still having similar issues when we load a API catalog page for the first time. (on a fresh browser session). That too intermittently and the second refresh always fix it.

**Comment by dknezicd** [comment]
Assuming you're using the smartdocs/1.1.0/main.js from gstatic.. As a workaround, use this locally and increase the timeout on line 162 
I believe I made this change for testing here https://github.com/dknezicd/apigee-api-catalog-drupal/commit/16225c9c5342d682552bea01a8707327aac5d76f#diff-32981a13284db7a021131df49e6cd203

**Comment by ravisilva** [comment]
this worked for us. many thanks @dknezicd

**Comment by cnovak** [comment]
I am going to reopen this issue so that we can fix this timeout issue which seems to be causing issues. Thanks @dknezicd for your info and @ravisilva for verifying.

**Comment by raakesh-blokhra** [comment]
@giteshk can you confirm if this needs to be worked on since there are API Catalog updates on the way? If so, please reopen this issue.
