### ISSUE TITLE
API product RBAC

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-api-catalog-drupal#71]
Share with chat channel so that Andrew P and others can review it.

**Comment by giteshk** [comment]
We want to maintain a 8.x-1.0 version with the old approach and 8.x-2.0 with the new content node approach

**Comment by cnovak** [comment]
We don't want to maintain the old version, but do want to give time for anyone that added features on top of the 1.0 version to move to 2.0 version. There would not be any breaking changes if you did not add any custom code, but in case someone does we need to bump major version to follow semantic versioning.

**Comment by giteshk** [comment]
@cnovak Any timeframe on when this will be available?

**Comment by cnovak** [comment]
We are very close to releasing a PR for this, you can subscribe to notifications to check when the PR is pushed up.

**Comment by m-khan23** [comment]
@cnovak @giteshk is there any work around for this? We are releasing API documentation for internal use on Monday 5/4 and have no way to hide it from external users at this point.

**Comment by giteshk** [comment]
@m-khan23 , Have you tried restricting access to your API Docs by changing "View published API docs"  permission to a targeted role. So Anonymous users don't get access to it?

**Comment by m-khan23** [comment]
@giteshk we aren't looking for a blanket policy. Here is the context:
Anonymous users: See API A, B, C
Users with 'External Role': See API A, B, C
Users with 'Internal Role': See API A, B, C **and** D

Even if there is a wonky technical work around, we are okay with that for now because as it stands today - we don't have a clean way to go live with API D on 5/4.

**Comment by kiranjyoth** [comment]
@m-khan23 Here is a way you can achieve this. 
If you have `/apis ` that will display all API docs of all products and users can see all published documentation. Which includes ABC&D. 
But If you enable classification of your API docs using a taxonomy term reference field, For example, refer to the screenshot 
![image](https://user-images.githubusercontent.com/1490213/80823174-fdede800-8b90-11ea-809d-aa0798b4cae4.png)
You can use a module (https://www.drupal.org/project/permissions_by_term) to set permissions on this node by making the taxonomy term not visible to certain roles. This permissions will trickle down to Node view, and Also views displays using node view permissions.

Hope that helps!

**Comment by m-khan23** [comment]
@kiranjyoth hey, thanks for the tips. While all other pages respect settings we have applied via the 'Permissions by Term' module, we have never been able to get the API catalog to play nice. I've tried what you have suggested again and no - go. 

Do you have a running example of this?

**Comment by kiranjyoth** [comment]
@m-khan23  I just spun this up on pantheon, and enabled the module, and enabled permissions on term **Data Append**  only to show for Roles **Authenticated** User
' http://dev-kickstart-885.pantheonsite.io/apis 
Now if you click on APIs **[Communication](http://dev-kickstart-885.pantheonsite.io/api/5)**, **[Geolink](http://dev-kickstart-885.pantheonsite.io/api/3)**, **[Inventory](http://dev-kickstart-885.pantheonsite.io/api/6)** or **[Service Location](http://dev-kickstart-885.pantheonsite.io/api/4)**  you will get access denied.  Let me know if this works the way you want it to.

**Comment by m-khan23** [comment]
@kiranjyoth Hmm. This solves half the issue. The other half would be not allowing the user to see the APIs they do not have access to at all.

I haven't been able to achieve what you have. Can you create me an admin account on your pantehon Drupal site so I can see what all configuration you have (i tried creating an account but it was disabled)? Maybe I am on an older version of the plugin or have a configuration mismatch... 

Thank you for the help!

**Comment by kiranjyoth** [comment]
@m-khan23 I haven't enabled Apigee Edge connection, which is why you were getting an error when trying to signup for an account, and I don't have an edge account that I can enable. so I enabled my trial account on this instance, Please go ahead and signup for a new account. Once you do that, I will disable my Edge account and give you admin access. 
Regarding the visibility on APIs page, I think we can add permissions either by a patch or config. I'll try it out.

**Comment by m-khan23** [comment]
@kiranjyoth Okay, i've attempted to create an account - pending your approval. Did not receive an email though with a password though....

Keep us updated about the API page visibility. I imagine that would be useful for a lot of folks... thank you!

**Comment by kiranjyoth** [comment]
@m-khan23 added you as admin. Yes, I will try a few things about APIs page and update here.

**Comment by m-khan23** [comment]
@kiranjyoth any luck on API page visibility? We were able to get the actual API access restriction working.

**Comment by kiranjyoth** [comment]
@m-khan23 I've spent some time to see what we can do here.

- Extend permissions by term module by extending functionality to API Docs entity type. (A custom module)

- Wait for https://github.com/apigee/apigee-api-catalog-drupal/pull/26 to be merged

- Try out tips suggested by @kscheirer [here](https://github.com/apigee/apigee-api-catalog-drupal/issues/55#issuecomment-560492421)

Other considerations here are API Docs module is being converted to content entities. This should solve several items in the issue queue. 
I haven't tried the solution  [here](https://github.com/apigee/apigee-api-catalog-drupal/issues/55#issuecomment-560492421) with taxonomy term applied on user and API doc, but you can give it a try and see if it works for you? 

Thanks

**Comment by m-khan23** [comment]
@kiranjyoth just to close this out. We tried the alternate method mentioned here without any luck. Ended up going live with RBAC for the API product and no API documentation published. Will wait for this release.

**Comment by cnovak** [comment]
@kiranjyoth , @giteshk: @arlina-espinoza just posted PR #71  for this if you want to help review and verify. By creating a new 2.0 version that uses node content type instead of a custom entity, you can use any of the existing node RBAC modules that already exist for nodes.

**Comment by arlina-espinoza** [comment]
Closed by #84 , which implements the API Catalog functionality using a node type, making it possible to use [permissions by term](https://www.drupal.org/project/permissions_by_term) or other node access control modules from contrib to implement RBAC.
