### ISSUE TITLE
Revisions delete option not available for API Docs

### ISSUE THREAD

**Issue by mrdhanasekaran89** [apigee/apigee-api-catalog-drupal#78]
I have some node contents and some API Docs in my Apigee portal. I am able to delete the revisions for the node contents. But in API Doc, I am not getting an option to delete revisions. Can you please do the needful fixes and update the Apigee distribution.

*Steps To Reproduce*
1. Go to Content->API Doc.
2. Click Edit in any of API Doc. 
3. Click Revisions Tab.
4. There is no option here to delete Revisions.

*Expected behavior*
To improve my performance of the portal, I don't want to keep many number of Revisions in the database. I am expecting to delete those Revisions as per my convenience. So please provide an option to delete Revisions.

*Screenshots*

![Revisions_issue](https://user-images.githubusercontent.com/50447235/78862203-6fd08700-7a54-11ea-8703-360650704e06.PNG)

Also if possible - please provide an option to delete all revisions at once in one button click.

*Version Info*
8.8.5 version

Thanks
M.Dhanasekaran

**Comment by cnovak** [comment]
I moved this to the API Catalog repo, and marked it for release 1.3 since I think our changes to move API Doc entities to being a Node content type will solve this issue.

**Comment by mrdhanasekaran89** [comment]
Hi @cnovak ,

Thanks for your response to my query. Are you planning to move the API Catalog entities to Content types? Can you please let us know when can I expect this update.

**Comment by cnovak** [comment]
Yes, we are. I forgot to link the ticket, here it is: #71 . You can follow that issue for updates, it is being worked on currently so should be out in a few weeks.
