### ISSUE TITLE
Change the names of the library in apigee_api_catalog.libraries.yml

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-api-catalog-drupal#82]
When referencing these libraries I have to use
apigee_api_catalog/apigee_api_catalog.smartdocs
apigee_api_catalog/apigee_api_catalog.smartdocs_integration

Can we change these so apigee_api_catalog doesn't have to be referenced twice.

**Comment by arlina-espinoza** [comment]
Closed by #86
