### ISSUE TITLE
Support for the AWS Gateway with the Devportal 

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-api-catalog-drupal#87]
Hi Team,

The requirement is we are setting up the developer portal for APIGEE with this kick-starter for publishing some proxies. We have some proxies that are built in AWS gateway and we wanted to get those proxies to be published  on the same developer portal. Is it a possibility. If so, What are the steps that are required to be followed.

One Drupal Developer Portal (APIGEE Kick-Starter) should support the APIGEE proxies as well as the AWS gateway proxies.

Thanks.

**Comment by arunz6161** [comment]
@pradeepgorle13 You can publish OpenAPI specs on devportals using the API Catalog module  (https://www.drupal.org/project/apigee_api_catalog) irrespective of where the API endpoint or the proxy resides. Hope this helps.

**Comment by pradeepgorle13** [comment]
@arunz6161 Like generating API key after they register. I know that Catalog should be fine but if i wanted to do some smart Doc's where they can test in developer portal itself. Also getting the information regarding the List of Proxies and Products they are tagged (since APIGEE developer portal has that we get to see the products). Is that a possibility ??

**Comment by cnovak** [comment]
You could list both the keys coming from Apigee and AWS, but you would need to create your own custom module to add this functionality.
