### ISSUE TITLE
Custom Endpoint usage on custom module

### ISSUE THREAD

**Issue by dhinakaran60** [apigee/apigee-api-catalog-drupal#89]
Hi Team,

Can you please provide the documentation or guide me on how to make the use Apigee connection object for my custom endpoints should be the part of custom module. or is there a way to fetch the API details associated with product on contributed module.

kindly help me the documentation will be helpful.

Regards,
Dhina

**Comment by cnovak** [comment]
Are you trying to get the details about an API spec entity in the API Catalog or are you trying to get API Product information? We have [documentation on how to work with entities that are mapped to the Apigee Edge API]( https://www.drupal.org/docs/8/modules/apigee-edge/apigee-edge-developer-guide).

**Comment by dhinakaran60** [comment]
Thanks a lot of the update.

I have done fetching the API Product information in one of my custom module using the below approach.
```
 // Getting the list of Product from apigee Endpoint.
    $api_product_storage = $this->entityTypeManager->getStorage('api_product');
    $api_products = $api_product_storage->loadMultiple();
     foreach ($api_products as $product_name => $product) {
        $product_names[$product_name]['proxies'] = $product->getProxies();
     }
```
From the API product we can get the proxies details using `getProxies()` method. How can get the proxies details further details like attributes,revision and swagger file associated?

Can you please help on above.

 is there a way to call the proxies details endpoint using Apigee connection object or any entity method available to get the proxies details.

Regards,
Dhina

**Comment by cnovak** [comment]
The Edge API has a resource for both getting proxy and proxy revision data. The details you need are in the [API Proxy Revision resource](https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/apis/%7Bapi_name%7D/revisions/%7Brevision_number%7D-1).  We have not added support to get proxy details in our [Apigee client for PHP](https://github.com/apigee/apigee-client-php), but would love to accept a contribution if you are up for it. Else, you can [make the call yourself using the Guzzle client that Drupal ships with](https://drupalize.me/blog/201512/speak-http-drupal-httpclient).

**Comment by cnovak** [comment]
I will close this for now, but comment back if you have more questions
