### ISSUE TITLE
Apigee Drupal 8 API Catalog module -Try this api form missing request parameters view

### ISSUE THREAD

**Issue by vinayporeddy** [apigee/apigee-api-catalog-drupal#90]
**Describe the bug**
Apigee Drupal 8 API Catalog module -Try this api from developer portal missing request parameters view

**To Reproduce**
1. Upload open api into developer portal
2. View shows missing request body option

**Expected behavior**
View request body should be visible along with  request parameters

**Screenshots**
![tryapi-screen](https://user-images.githubusercontent.com/22528858/84087491-1080eb80-a99f-11ea-861b-6bff045a1391.jpeg)

**Additional context**

**Version Info**
Drupal 8.8.5
drupal/apigee_api_catalog                1.2.0      Apigee API Catalog for Drupal
drupal/apigee_edge                       1.10.0       Apigee Edge for Drupal.

**Comment by arunz6161** [comment]
I was able to reproduce the issue both in Integrated portals and Drupal, so this issue probably is upstream coming from SmartDocs code. @vinayporeddy could you try using the swagger UI as a workaround and see if that helps : https://www.drupal.org/docs/8/modules/apigee-api-catalog/customize-your-api-catalog.

The associated bug is being worked but at this stage there is no ETA.

**Comment by raakesh-blokhra** [comment]
Closing this issue. Please reopen it if the issue still exists.  Thanks
