### ISSUE TITLE
New Module Installation issues via Devportal UI

### ISSUE THREAD

**Issue by vinayporeddy** [apigee/apigee-api-catalog-drupal#92]
**Describe the bug**
When we try to install new Module Installation  via Devportal UI we see below error.
An AJAX HTTP error occurred.
HTTP Result Code: 403
Debugging information follows.
Path: /core/authorize.php/core/authorize.php?batch=1&id=114&op=do_nojs&op=do
StatusText: Forbidden
ResponseText: 
403 Forbidden
403 Forbidden
nginx/1.16.1

https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud

Below configuration in nginx didn't help
https://www.drupal.org/project/drupal/issues/2583799

**To Reproduce**
1.Login to developer portal
2.Navigate to extend -> install new module (admin/modules/install)
3. Choose zip file and click on install
4. We see error 
==

    Notice: Undefined index: log in update_authorize_install_batch_finished() (line 293 of core/modules/update/update.authorize.inc).

    update_authorize_install_batch_finished(, Array, Array, Object) (Line: 456)
    _batch_finished() (Line: 98)
    _batch_page(Object) (Line: 169)

    Warning: Invalid argument supplied for foreach() in update_authorize_install_batch_finished() (line 293 of core/modules/update/update.authorize.inc).

    update_authorize_install_batch_finished(, Array, Array, Object) (Line: 456)
    _batch_finished() (Line: 98)
    _batch_page(Object) (Line: 169)

    Notice: Undefined index: log in update_authorize_install_batch_finished() (line 334 of core/modules/update/update.authorize.inc).

    update_authorize_install_batch_finished(, Array, Array, Object) (Line: 456)
    _batch_finished() (Line: 98)
    _batch_page(Object) (Line: 169)

    Notice: Undefined index: tasks in update_authorize_install_batch_finished() (line 335 of core/modules/update/update.authorize.inc).

    update_authorize_install_batch_finished(, Array, Array, Object) (Line: 456)
    _batch_finished() (Line: 98)
    _batch_page(Object) (Line: 169)

    Installation failed! See the log below for more information.
==

**Expected behavior**
Should able to install module successfully

**Screenshots**
<img width="429" alt="image" src="https://user-images.githubusercontent.com/22528858/84312122-4a75fd00-ab19-11ea-9ce2-e8f93d3df4ac.png">

**Additional context**
NA

**Version Info**
Drupal Version
8.8.5
Web Server
nginx/1.16.1 
PHP
Version
7.3.11

**Comment by kiranjyoth** [comment]
@vinayporeddy Recommended way to install modules is via composer. Please refer here, https://www.drupal.org/docs/extending-drupal/installing-drupal-modules 

For better maintainability here is a sample CI workflow that works for most of our customers. 
1. Source control like github, gitlab is used for kickstart code. (exclude settings.php from source code to secure DB keys etc)
2. Clone the repo locally, add modules using composer `composer require drupal/'module_name'`
3. Commit to you repo
4. Deploy repo to your web server
5. Go to admin/modules/ and enable the module you added. 

Hope that helps.
p.s. @cnovak possible to move this issue to kickstart project, as its unrelated to API catalog ?
