### ISSUE TITLE
API Catalog page layout is broken

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-api-catalog-drupal#93]
API Catalog page layout is broken

**Expected behavior**
-NA

**Screenshots**
go to https://api-cat-2x-sai-demo.pantheonsite.io/apis,

![catalog](https://user-images.githubusercontent.com/4381612/85055749-ea9fd780-b152-11ea-8efc-1c7d74fa935e.png)

**Comment by arlina-espinoza** [comment]
Ah yes, this is because a kickstart portal was manually configured to use the 2.x version of apigee_api_catalog. It should be fixed as part of https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/363 .
