### ISSUE TITLE
File Link 8.x-1.7 is no longer supported

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-api-catalog-drupal#94]
# Description
The [File Link](https://www.drupal.org/project/file_link) module needs to be upgraded to 2.0

<img width="687" alt="Screen Shot 2020-06-25 at 6 24 55 AM" src="https://user-images.githubusercontent.com/613093/85728265-9a71c980-b6ac-11ea-8433-baf6c7fdc5b1.png">

**Comment by arlina-espinoza** [comment]
Closed by #96 .
