### ISSUE TITLE
drush updb gives error Update aborted by: apigee_api_catalog_update_8804

### ISSUE THREAD

**Issue by jjmackow** [apigee/apigee-api-catalog-drupal#95]
Upgraded the  Apigee_api_catalog from 1.2 to 2.2 through composer ... but after running drush updb, I got the error:
[error]  Update aborted by: apigee_api_catalog_update_8804 

 apigee_api_c   8804        hook_update_n   Convert API Doc entities to nodes (migrating data) if updating from 1.x.  

**To Reproduce**
We are using Apigee Kickstart 1.7, and the apigee catalog is part of that profile.  Coposer installs everything fine but when I run drush updt then it fails.

We are using Drupal 8.91.

**Comment by arunz6161** [comment]
Thanks for reporting this issue @jjmackow . We will prioritize this soon and get back to you if we need more information.

**Comment by wheatpenny** [comment]
I get a similar error. Running "drush updb" gives the following output:

>  [notice] Update started: apigee_api_catalog_update_8804
>  [error]  Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'canonical' found for the 'apidoc' entity type in Drupal\Core\Entity\EntityBase->toUrl() (line 227 of /app/docroot/core/lib/Drupal/Core/Entity/EntityBase.php). 
>  [error]  No link template 'canonical' found for the 'apidoc' entity type 
>  [error]  Update failed: apigee_api_catalog_update_8804 
 [error]  Update aborted by: apigee_api_catalog_update_8804

**Comment by arlina-espinoza** [comment]
@jjmackow / @wheatpenny : I've posted a PR that should fix this error: #97
