### ISSUE TITLE
drupal/file_link module conflicting on composer update

### ISSUE THREAD

**Issue by heykarthikwithu** [apigee/apigee-api-catalog-drupal#99]
We have a new Security release on file_link in 8.2.x
https://www.drupal.org/project/file_link/releases/2.0.0

We have as 8.1.x in the apigee-api-catalog-drupal
`        "drupal/file_link": "~1.0"`

For this reason, we see conflict while running the composer update

We should have 8.2.x in the composer json in apigee-api-catalog-drupal

**Comment by arlina-espinoza** [comment]
@heykarthikwithu The latest release [8.x-2.3](https://www.drupal.org/project/apigee_api_catalog/releases/8.x-2.3) now requires file_link ^2.0.
